import ISkjema from "components/Skjema/models/ISkjema";
import DefaultProsjekt from "../../Prosjekt/types/DefaultProsjekt";

const DefaultSkjema: ISkjema = {
    skjemaNavn: '',
    skjemaKortNavn: '',
    delProduktNummer: '',
    undersokelseType: '',
    aktivertForIntervjuing: false,
    intervjuTypeTelefon: false,
    intervjuTypeBesok: false,
    intervjuTypeWeb: false,
    slettesEtterRetur: false,
    intervjuTypePapir: false,
    oppstartDataInnsamling: new Date(),
    klarTilGenerering: false,
    klarTilUtsending: false,
    status: '',
    planlagtSluttDato: new Date(),
    sluttDato: new Date(),
    overtid: false,
    onsketSvarProsent: 0,
    dataUttaksDato: new Date(),
    hentAlleOppdrag: false,
    kanSlettesLokalt: false,
    langtidsLagretAv: '',
    langtidsLagretDato: new Date(),
    antallIntervjuObjekterLagret: 0,
    antallOppdragLagret: 0,
    intervjuVarighet: 0,
    adminTid: 0,
    regoverforingDato: new Date(),
    regoverforingInitialer: '',
    regoverforingSeksjon: '',
    ioBrevGodkjentInitialer: '',
    krypteringDato: new Date(),
    krypteringMailSendt: new Date(),
    anonymDato: new Date(),
    anonymMailSendt: new Date(),
    ryddDato: new Date(),
    ryddMailSendt: new Date(),
    papirMakuleringDato: new Date(),
    papirMakuleringMailSendt: new Date(),
    maxAntIntervjuObjekterKontakt: 0,
    malVersjon: 0,
    kommentar: '',
    instrumentId: '',
    altIBlaise5: false,
    prosjekt: DefaultProsjekt,
}

export default DefaultSkjema;